name: Release
on:
  push:
    branches:
        - release
jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
        NODE_ENV: testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
            key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
            path: |
                **/node_modules
      - run: make test
      - run: npm install
      - run: npm run test

  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: 'ghcr.io/oplyio/oplyserver:dev'